#!/bin/bash
echo "Backup Started at:"
echo `date`
echo "Movie backup started at:"
echo `date +%T`
rsync -Phaq --exclude /.Spotlight-V100/ /Volumes/Movies/ /Volumes/Movies\ Backup

echo "Amy Jo's File backup started at:"
echo `date +%T`
rsync -Phaq --exclude /.Spotlight-V100/ /Volumes/Amy\ Jo\'s\ Drive/ /Volumes/Amy\ Jo\'s\ Backup

echo "Joe's File backup started at:"
echo `date +%T`
rsync -Phaq --exclude /Backups.backupdb/ --exclude /Pictures/Photos\ Library.photoslibrary/ --exclude /.Spotlight-V100/ /Volumes/Joe\'s\ Drive/ /Volumes/Joe\'s\ Backup

echo "Picture backup started at:"
echo `date +%T`
rsync -Phaq --delete /Volumes/Joe\'s\ Drive/Pictures/ /Volumes/Joe\'s\ Backup/Pictures

echo "Backup ended at:"
echo `date`
