#!/bin/bash
#rsync -rv --progress --dry-run /Volumes/Movies/ /Volumes/Movies\ Backup
rsync -a --progress /Volumes/Movies/ /Volumes/Movies\ Backup
#rsync -rv --progress --dry-run /Volumes/Amy\ Jo\'s\ Drive/ /Volumes/Amy\ Jo\'s\ Backup
rsync -a --progress /Volumes/Amy\ Jo\'s\ Drive/ /Volumes/Amy\ Jo\'s\ Backup
#rsync -rv --progress --dry-run /Volumes/Joe\'s\ Mac\ mini\ HDD/Music /Volumes/Joe\'s\ Drive
#rsync -a --progress /Volumes/Joe\'s\ Mac\ mini\ HDD/Music /Volumes/Joe\'s\ Drive
#rsync -rv --progress --dry-run --exclude /Backups.backupdb/ /Volumes/Joe\'s\ Drive/ /Volumes/Joe\'s\ Backup
rsync -a --progress --exclude /Backups.backupdb/ --exclude /Pictures/Photos\ Library.photoslibrary/ --exclude /.Spotlight-V100/ /Volumes/Joe\'s\ Drive/ /Volumes/Joe\'s\ Backup
